# Generated by Django 5.0.6 on 2024-06-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goofy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
