# Generated by Django 5.0.6 on 2024-08-07 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goofy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('nonce', models.IntegerField()),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('previous_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_blocks', to='goofy_app.block')),
                ('transactions', models.ManyToManyField(to='goofy_app.transaction')),
            ],
        ),
    ]
