# Generated by Django 5.0.6 on 2024-08-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goofy_app', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guest',
            field=models.BooleanField(default=False),
        ),
    ]
