# Generated by Django 5.0.6 on 2024-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goofy_app', '0002_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
