# Generated by Django 5.0.6 on 2024-08-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goofy_app', '0003_user_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
