# Generated by Django 5.0.6 on 2024-11-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goofy_app', '0004_user_google_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
