# Generated by Django 5.0.6 on 2024-11-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goofy_app', '0005_user_code_generated_at_user_password_reset_code_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['sender'], name='goofy_app_t_sender__23affd_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['recipient'], name='goofy_app_t_recipie_0c2019_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['timestamp'], name='goofy_app_t_timesta_2861f1_idx'),
        ),
    ]
